/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_laziestcoder_jmbus_JMeterBusService */

#ifndef _Included_com_github_laziestcoder_jmbus_JMeterBusService
#define _Included_com_github_laziestcoder_jmbus_JMeterBusService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_laziestcoder_jmbus_JMeterBusService
 * Method:    decodeHexValueString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_laziestcoder_jmbus_JMeterBusService_decodeHexValueString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
