/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_laziestcoder_jmbus_JMeterBusService */

#ifndef _Included_com_laziestcoder_jmbus_JMeterBusService
#define _Included_com_laziestcoder_jmbus_JMeterBusService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_laziestcoder_jmbus_JMeterBusService
 * Method:    decodeHexValueFromCLibrary
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_laziestcoder_jmbus_JMeterBusService_decodeHexValueFromCLibrary
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
